version: '3.7'

services:
  keymind:
    build: .
    command: gunicorn wsgi:app -w 2 --bind 0.0.0.0:5000 server --error-logfile error.log --access-logfile access.log --capture-output --log-level debug
    volumes:
      - ./:/app
    ports:
      - 5000:5000

#docker-compose up -d
#docker-compose down