version: '3.7'

services:
  keymind:
    build: .
    command: gunicorn -w 2 --log-level INFO --access-gfile access.log --error-logfile error.log --bind 0.0.0.0:5000 wsgi:app
    volumes:
      - ./:/app
    ports:
      - 5000:5000

#docker-compose up -d
#docker-compose down