version: '3.7'

services:
  keymind:
    build: .
    command: gunicorn wsgi:app -w 2 --bind 0.0.0.0:5000 --log-level INFO --log-file gunicorn.log
    volumes:
      - ./:/app
    ports:
      - 5000:5000

#docker-compose up -d
#docker-compose down