version: '3.7'

services:
  keymind:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app #flask run --host=0.0.0.0
    volumes:
      - ./:/app
    ports:
      - 5000:5000

#docker-compose up -d
#docker-compose down