import enum


class TansiyonEnum(enum.Enum):
    """ """

    YUKSEK_TANSIYON = "YUKSEK_TANSİYON",
    YUKSEK_TANSIYON_HIPERTENSIYON_ASAMA_1 = "YÜKSEK TANSİYON HİPERTENSİYONU AŞAMA-1",
    YUKSEK_TANSIYON_HIPERTENSIYON_ASAMA_2 = "YÜKSEK TANSİYON HİPERTENSİYONU AŞAMA-2",
    HIPERTENSIF_KRIZLER = "HİPERTENSİF KRİZLER"
