import enum


class BloodPressureEnum(enum.Enum):
    """ """

    HIGH_BLOOD_PRESSURE = "HIGH BLOOD PRESSURE"
    HIGH_BLOOD_PRESSURE_HYPERTENSION_STAGE_1 = "HIGH BLOOD PRESSURE HYPERTENSION STAGE-2"
    HIGH_BLOOD_PRESSURE_HYPERTENSION_STAGE_2 = "HIGH BLOOD PRESSURE HYPERTENSION STAGE-2"
    HYPERTENSION_CRISIS = "HYPERTENSION CRISIS"
